### PR TITLE
Fix system tests

### PR DESCRIPTION
**Pull request by gofraser**
A first bunch of fixes for failing system tests.

### CODE REVIEW

**Comment by gofraser** [comment]
Merging this so that CI results are ready in the morning...

**Review by schweikl — COMMENTED** [review]
This change entails that all subclasses of `SearchListener` should now have a `serialVersionUID` field as well, doesn't it?

**Comment by gofraser** [comment]
Yes -- otherwise the system tests will fail as the entire GA is serialised/deserialised. Is there a problem with this?

**Comment by schweikl** [comment]
I think making `SearchListener` serializable is fine. But I would also add an explicit `serialVersionUID` value in all implementing subclasses of `SearchListener`. I can take care of this if you want to.

**Comment by schweikl** [comment]
I created a pull request that would fix this: #30

**Pull request merged**
