### PR TITLE
Add copy constructors for SearchListeners

### LINKED ISSUE #15: Copy Constructor for Search Listeners
### Overview

Search Listener has a genetic Type parameter, that defines the Type of the observed Genetic algorithm.

A TestSuiteAdapter needs to map those Stopping conditions from SearchListener<TestSuiteChromosome> to SearchListener<TestChromosome> and preserve the current state.

A possibility to add such a mapping would be to add a copy Constructor (that is independent of the generic type) to all Search Listeners.

e.g:
```
public MaxGenerationStoppingCondition(MaxGenerationStoppingCondition<?> other) {
	this.currentIteration = other.currentIteration;
	this.maxIterations = other.maxIterations;
}
```

The advantage of this solution would be, that the logic of copying the state of the SearchListener, would be inside the class and the TestSuiteAdapter only has to call the copy constructor (in contrast to create a new Listener and copy the state with Getter and Setter Methods).

The main drawback is, that the changes have to be made in a lot of classes:

- [x] BranchCoverageMap *(singleton)*
- [x] DiversityObserver
- [x] FitnessLogger
- [x] FunctionalSearchListener
- [x] GlobalTimeStoppingCondition
- [x] LocalSearchBudget *(singleton)*
- [x] MaxFitnessEvaluationsStoppingCondition
- [x] MaxGenerationStoppingCondition
- [x] MaxLengthStoppingCondition
- [x] MaxStatementsStoppingCondition
- [x] MaxTestsStoppingCondition
- [x] MaxTimeStoppingCondition
- [x] MutationTestPool *(only contains static fields)*
- [x] MutationTimeoutStoppingCondition
- [x] ProgressMonitor
- [x] RMIStoppingCondition *(singleton)*
- [x] RelativeSuiteLengthBloatControl
- [x] RelativeTestLengthBloatControl
- [x] ResourceController
- [x] ShutdownTestWriter
- [x] SocketStoppingCondition
- [x] StatisticsListener
- [x] StoppingCondition *(interface)*
- [x] StoppingConditionImpl *(abstract class)*
- [x] SuiteFitnessEvaluationListener
- [x] TestCaseRecycler *(singleton)*
- [x] TimeDeltaStoppingCondition
- [x] ZeroFitnessStoppingCondition

### Contributing
Please push your changes to [`15-copy-constructor-for-search-listeners`](https://github.com/VoglSebastian/evosuite/tree/15-copy-constructor-for-search-listeners)

### PR DESCRIPTION
**Pull request by schweikl**
Fixes #15

### CODE REVIEW

**Comment by schweikl** [comment]
@VoglSebastian Could you please review the changes made by this pull request? In particular:

- Does every `SearchListener` contain an appropriate copy constructor?
- Some `SearchListener`s only have static fields. Here, I created "empty" default constructors for the sake of completeness. Is this OK?
- Some `SearchListener`s are singletons. Here, I did **not** implement a copy constructor (it doesn't make sense to have one). 
- `RMIStoppingCondition` is a singleton, too. But here, the `StoppingCondition` forces me to implement `clone()`. I simply throw an `UnsupportedOperationException`. (Instead of `CloneNotSupportedException since that is a checked exception that is not declared by `PublicCloneable::clone`). Is that OK?
- The copy constructor for `StatisticsListener` is a little bit tricky due to the `private volatile Thread notifier` field. Please check whether the implementation of that constructor is OK.
- `ResourceController` contains a field `private GeneticAlgorithm<T> ga`. I cannot make a deep copy of the entire GA (to this, we would have to create copy ctors for `GeneticAlgorithm`), so I just made a shallow copy. Is that OK?
- `FunctionalSearchListener` contains a handful of `Consumer<GeneticAlgorithm<T>>` fields. Here, I also did not make deep copies, just shallow ones. (I did not know how to make deep copies.) Is that OK?
- Are there any problems you noticed in the implementation? Is there anything else that seems no OK yet? Is there something else that should be discussed before merging this PR?

**Review by VoglSebastian — COMMENTED** [review]
I am concerned about the SocketStoppingCondition, since only 1 instance can open the Socket in the accept method. We may add a static field boolean isStarted and make the field interrupted static as well.
I don't think it was intended that there can be more than 1 instance of this class. Therefore, all instances should know when the search is interrupted.

**Comment by schweikl** [comment]
That's a good point. Can you take care of this @VoglSebastian ?

**Comment by schweikl** [comment]
If I am not mistaken we could also make `SocketStoppingCondition` a singleton, just like `RMIStoppingCondition`, can't we? What you're saying makes sense to me, and I agree, there should only be one instance that opens the socket. Surely, we cannot make everything in `RMIStoppingCondition` static because we still need to implement the interface `StoppingCondition`. I guess that having only two static fields `isStarted` and `interrupted` as you suggested would do the trick. But on the other hand, this doesn't prevent you from creating more than one instance of an `RMIStoppingCondition`. And to me, having the state of an object scattered across several instances and the static class object is not the cleanest approach. At least not when there are alternative approaches; I still believe this is a good use case for the singleton pattern. Yes, you will have the unchecked cast in `getInstance()` (just like we discussed in #23). But then again, it also doesn't cause any harm. But I am open to further suggestions, maybe there are some reasons against the singleton pattern that I don't see right now.

**Comment by schweikl** [comment]
Well, I just found one drawback of the singleton pattern: we have to implement `clone()` as follows:
```Java
@Override
public StoppingCondition<T> clone() {
	throw new UnsupportedOperationException("cannot clone singleton");
}
```
That's not particularly nice...

**Comment by schweikl** [comment]
For testing purposes I created a new branch ([`socket-stopping-condition-singleton`](https://github.com/VoglSebastian/evosuite/tree/socket-stopping-condition-singleton)) with the changes outlined above. But I only ran one experiment so far. I used class `Menu` from `47_dvd-homevideo` and these command line parameters:
```
-Dalgorithm=DynaMOSA -Dstrategy=MOSuite -generateMOSuite -Dclient_on_thread=true -Dsearch_budget=5 -Dstopping_port=13375
```
It seems that the security manager prevents the socket from being opened:
```
Exception in thread "Thread-6" java.lang.SecurityException: Security manager blocks ("java.net.SocketPermission" "localhost:13375" "listen,resolve")
java.lang.Thread.getStackTrace(Thread.java:1559)
org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
java.net.ServerSocket.bind(ServerSocket.java:389)
java.net.ServerSocket.<init>(ServerSocket.java:252)
java.net.ServerSocket.<init>(ServerSocket.java:143)
org.evosuite.ga.stoppingconditions.SocketStoppingCondition.lambda$accept$0(SocketStoppingCondition.java:80)
java.lang.Thread.run(Thread.java:748)

	at org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:452)
	at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
	at java.net.ServerSocket.bind(ServerSocket.java:389)
	at java.net.ServerSocket.<init>(ServerSocket.java:252)
	at java.net.ServerSocket.<init>(ServerSocket.java:143)
	at org.evosuite.ga.stoppingconditions.SocketStoppingCondition.lambda$accept$0(SocketStoppingCondition.java:80)
	at java.lang.Thread.run(Thread.java:748)
```
Apart from that, the adaptation of the `SocketStoppingCondition` in `TestSuiteAdapter` seems to work fine. If you got time, maybe you could take a look at it and give me some feedback if you like?

**Comment by schweikl** [comment]
Expanding the discussion we already had in #23 allow me to make one additional note to give you some peace of mind. In the `StoppingCondition` interface the type parameter `T` appears primarily in a contra-variant position. In a language that supports declaration-site variance (e.g. Scala or Kotlin) one would probably already declare the `T` as contra-variant type parameter in the interface signature. That is:
```Scala
trait SearchListener[-T]
```
in Scala and
```Kotlin
interface SearchListener<in T>
```
in Kotlin. This means that a hypothetical `SearchListener<Chromosome>` would actually be a **subtype** of a `SearchListener<TestChromosome>` and `SearchListener<TestSuiteChromosome>`. This is sound because a `SearchListener` that accepts `Chromosome`s can also deal with `TestSuiteChromosome`s and `TestChromosome`. But the other way round, a `SearchListener` that accepts `TestChromosome` does not work with other `Chromosome`s.

Thus, an unchecked cast such as
```Java
@SuppressWarnings("unchecked")
public static <T extends Chromosome<T>> SocketStoppingCondition<T> getInstance() {
	if (instance == null)
		instance = new SocketStoppingCondition<>();
	return (SocketStoppingCondition<T>) instance;
}
```
just emulates this behavior. A `SearchListener` doesn't care what a `T` is, since by construction it works with all sorts of `T`s. So, why shouldn't you be able to freely cast the `T` to something else? Admittedly, the cast is a hack to work around the lack of declaration-site variance in Java but I think it's justified because type theory tells us that it works. I suppose the closest you could get is to declare
```Java
public class SocketStoppingCondition implements StoppingCondition<Chromosome>
```
and then use more raw types in the implementation of the interface methods like 
```Java
	public void searchStarted(GeneticAlgorithm algorithm) {
		// Auto-generated method stub
	}
```
But then again, this does not work for us because `Chromosome` is self-typed. So, the compiler will complain that `Chromosome` is not within its bound. Saying
```Java
public class SocketStoppingCondition implements StoppingCondition<? extends Chromosome<?>>
```
instead also doesn't work because the compiler does not expect a wildcard (`?`).

**Pull request merged**
